project:
  type: website

website:
  title: "Reproducible Workflows Workshops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - workshop-dates.qmd
      - presentations.qmd
      - tutos.qmd
      - thanks.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/CeresBarros/reproducible-workflowsWS
          - text: Report a bug
            url: https://github.com/CeresBarros/reproducible-workflowsWS/Issues
    side-bar:
      collapse-level: 4
      style: floating
  page-footer:
    right:
      - text: "Powered by Quarto"
    left:
      - text: "Future Forest Ecosystems Centre, BC Ministry of Forests"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    html-math-method: katex

bibliography: references.bib

execute:
  freeze: auto