project:
  type: website

website:
  title: "Reproducible workflows"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - workshop-dates.qmd
      - presentations.qmd
      - tutos.qmd
      - thanks.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://....
          - text: Report a bug
            url: https://..../Issues
    side-bar:
      collapse-level: 4
      style: floating
  body-footer: |
    Powered by [Quarto](https://quarto.org/)

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    html-math-method: katex

bibliography: references.bib

execute:
  freeze: auto